/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tablet.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tablet(props) {
  const { nodes, materials } = useGLTF("/models/tablet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials.Display} />
      <mesh
        geometry={nodes.Plane001_1.geometry}
        material={materials.Glass_backside}
      />
      <mesh
        geometry={nodes.Plane001_2.geometry}
        material={materials.Tablet_white}
      />
      <mesh geometry={nodes.Plane001_3.geometry} material={materials.Handle} />
    </group>
  );
}

useGLTF.preload("/models/tablet.glb");
